version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: snake-redis
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: snake-the-game/server/Dockerfile
    container_name: snake-server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
